import { type NextRequest, NextResponse } from "next/server";
import { getServerSession } from "@/lib/auth";
import prisma from "@/lib/prisma";

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const session = await getServerSession();
    if (!session?.user?.id) {
      return NextResponse.json(
        { error: { code: "UNAUTHORIZED", message: "Authentication required" } },
        { status: 401 },
      );
    }

    const { id } = await params;

    const report = await prisma.report.findUnique({
      where: { id },
      include: {
        investigation: {
          select: { id: true, url: true, depth: true, userId: true, completedAt: true },
        },
      },
    });

    if (!report) {
      return NextResponse.json(
        { error: { code: "NOT_FOUND", message: "Report not found" } },
        { status: 404 },
      );
    }

    if (report.investigation.userId !== session.user.id) {
      return NextResponse.json(
        { error: { code: "FORBIDDEN", message: "Not authorized" } },
        { status: 403 },
      );
    }

    const findings = await prisma.finding.findMany({
      where: { investigationId: report.investigationId },
      orderBy: [{ severity: "asc" }, { createdAt: "desc" }],
    });

    const md = [
      `# Marten Investigation Report`,
      ``,
      `**URL:** ${report.investigation.url}`,
      `**Depth:** ${report.investigation.depth}`,
      `**Score:** ${report.overallScore ?? "N/A"}/100`,
      `**Completed:** ${report.investigation.completedAt?.toISOString() ?? "N/A"}`,
      ``,
      `## Summary`,
      ``,
      report.summary,
      ``,
      `## Findings (${findings.length})`,
      ``,
      ...findings.map(
        (f, i) =>
          `### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}\n\n` +
          `${f.description}\n\n` +
          `- **Severity:** ${f.severity}\n` +
          `- **Category:** ${f.category}\n` +
          `- **Confidence:** ${(f.confidence * 100).toFixed(0)}%\n` +
          `- **Source:** ${f.source}\n` +
          ((f as { recommendation?: string }).recommendation ? `- **Recommendation:** ${(f as { recommendation?: string }).recommendation}\n` : ""),
      ),
      ``,
      `---`,
      `*Generated by Marten Investigation Platform*`,
      ``,
    ].join("\n");

    return new Response(md, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="marten-report-${id}.md"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Export failed";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 },
    );
  }
}
