import { Types } from "mongoose";
import { type NextRequest, NextResponse } from "next/server";
import { getServerSession } from "@/lib/auth";
import { investigationRepo } from "@/lib/repositories/investigation.repository";
import type { Finding } from "@/types";

export async function GET(
  _request: NextRequest,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const session = await getServerSession();
    if (!session?.user?.id) {
      return NextResponse.json(
        { error: { code: "UNAUTHORIZED", message: "Authentication required" } },
        { status: 401 },
      );
    }

    const { id } = await params;

    const investigation = await investigationRepo.findByReportId(id);

    if (!investigation || !investigation.report) {
      return NextResponse.json(
        { error: { code: "NOT_FOUND", message: "Report not found" } },
        { status: 404 },
      );
    }

    const inv = investigation as typeof investigation & { _id: Types.ObjectId };

    if (inv.userId?.toString() !== session.user.id) {
      return NextResponse.json(
        { error: { code: "FORBIDDEN", message: "Not authorized" } },
        { status: 403 },
      );
    }

    const report = inv.report!;
    const findings = (report.findings ?? []) as unknown as Finding[];

    const md = [
      `# Marten Investigation Report`,
      ``,
      `**URL:** ${inv.url}`,
      `**Depth:** ${inv.depth}`,
      `**Score:** ${report.overallScore ?? "N/A"}/100`,
      `**Completed:** ${inv.completedAt?.toISOString?.() ?? inv.completedAt ?? "N/A"}`,
      ``,
      `## Summary`,
      ``,
      report.summary,
      ``,
      `## Findings (${findings.length})`,
      ``,
      ...findings.map(
        (f, i) =>
          `### ${i + 1}. [${f.severity.toUpperCase()}] ${f.title}\n\n` +
          `${f.description}\n\n` +
          `- **Severity:** ${f.severity}\n` +
          `- **Category:** ${f.category}\n` +
          `- **Confidence:** ${(f.confidence * 100).toFixed(0)}%\n` +
          `- **Source:** ${f.source}\n` +
          ((f as { recommendation?: string }).recommendation ? `- **Recommendation:** ${(f as { recommendation?: string }).recommendation}\n` : ""),
      ),
      ``,
      `---`,
      `*Generated by Marten Investigation Platform*`,
      ``,
    ].join("\n");

    return new Response(md, {
      headers: {
        "Content-Type": "text/markdown; charset=utf-8",
        "Content-Disposition": `attachment; filename="marten-report-${id}.md"`,
      },
    });
  } catch (err) {
    const message = err instanceof Error ? err.message : "Export failed";
    return NextResponse.json(
      { error: { code: "INTERNAL_ERROR", message } },
      { status: 500 },
    );
  }
}
